---
- hosts: all
  gather_facts: False
  vars:
    BASE_DIR: /home/web/spacescoop
    BASE_DIR_LOCAL: "{{ lookup('env','UNAWE_BASE') }}spacescoop"
    REMOTE_DIR: 
  tasks:
    # - name: copy mysql db file to remote
    #   copy: src=/Users/rino/Projects/astroEDU/database-latest.sql dest=/tmp/database-latest-dev.sql
    # - name: import mysql database from file
    #   mysql_db: 
    #     name: spacescoop
    #     state: import 
    #     target: /tmp/database-latest-dev.sql
    #     login_user: "{{ DATABASE_USER_PROD }}"
    #     login_password: "{{ DATABASE_PASSWORD_PROD }}"
    - name: copy uploaded files
      synchronize:
        src: "{{ BASE_DIR_LOCAL }}_uploads/"
        dest: "{{ BASE_DIR }}_uploads"
